/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject2;

import Dao.CategoryDao;
import Dao.ProductDao;
import Model.Category;
import Model.Product;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Ravindu
 */
public class AddNewProductGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddNewProductGUI
     */
    public AddNewProductGUI() {
        initComponents();
        btnSave.setEnabled(false);
    }

    public void validateFields() {
        String name = txtName.getText();
        String price = txtPrice.getText();
        if (!name.equals("") && !price.equals("")) {
            btnSave.setEnabled(true);
        } else {
            btnSave.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCategory = new javax.swing.JComboBox<>();
        txtPrice = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnEnglish = new javax.swing.JButton();
        btnFrench = new javax.swing.JButton();
        btnGerman = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 134));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\new product.png")); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("AddNewProductGUI.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\close.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(bundle.getString("AddNewProductGUI.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 104, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(bundle.getString("AddNewProductGUI.jLabel3.text")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(bundle.getString("AddNewProductGUI.jLabel4.text")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 218, -1, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 101, 332, -1));

        txtCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCategoryKeyReleased(evt);
            }
        });
        getContentPane().add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 157, 332, -1));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 215, 332, -1));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\save.png")); // NOI18N
        btnSave.setText(bundle.getString("AddNewProductGUI.btnSave.text")); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 287, -1, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\clear.png")); // NOI18N
        btnClear.setText(bundle.getString("AddNewProductGUI.btnClear.text")); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 287, -1, -1));

        btnEnglish.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnglish.setText(bundle.getString("AddNewProductGUI.btnEnglish.text")); // NOI18N
        btnEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnglishActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 50, -1));

        btnFrench.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFrench.setText(bundle.getString("AddNewProductGUI.btnFrench.text")); // NOI18N
        btnFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrenchActionPerformed(evt);
            }
        });
        getContentPane().add(btnFrench, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 50, -1));

        btnGerman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGerman.setText(bundle.getString("AddNewProductGUI.btnGerman.text")); // NOI18N
        btnGerman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGermanActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerman, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 50, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\Coffee_Grain_Wood_planks_564164_1366x768 - Copy.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtCategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoryKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtCategoryKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<Category> list = CategoryDao.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while (itr.hasNext()) {
            Category categoryObj = itr.next();
            txtCategory.addItem(categoryObj.getName());
        }
    }//GEN-LAST:event_formComponentShown

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Product product = new Product();
        product.setName(txtName.getText());
        product.setCategory((String) txtCategory.getSelectedItem());
        product.setPrice(txtPrice.getText());
        ProductDao.save(product);
        setVisible(false);
        new AddNewProductGUI().setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddNewProductGUI().setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtPriceKeyReleased

    private void btnEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnglishActionPerformed
        // TODO add your handling code here:
        Locale l = new Locale("en", "US");
        ResourceBundle r = ResourceBundle.getBundle("Bundle", l);
        jLabel3.setText(r.getString("AddNewProductGUI.jLabel3.text"));
        jLabel2.setText(r.getString("AddNewProductGUI.jLabel2.text"));
        jLabel1.setText(r.getString("AddNewProductGUI.jLabel1.text"));
        btnClear.setText(r.getString("AddNewProductGUI.btnClear.text"));
        btnSave.setText(r.getString("AddNewProductGUI.btnSave.text"));
        jLabel4.setText(r.getString("AddNewProductGUI.jLabel4.text"));
    }//GEN-LAST:event_btnEnglishActionPerformed

    private void btnFrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrenchActionPerformed
        // TODO add your handling code here:
        Locale l = new Locale("fr", "FR");
        ResourceBundle r = ResourceBundle.getBundle("Bundle", l);
        jLabel3.setText(r.getString("AddNewProductGUI.jLabel3.text"));
        jLabel2.setText(r.getString("AddNewProductGUI.jLabel2.text"));
        jLabel1.setText(r.getString("AddNewProductGUI.jLabel1.text"));
        btnClear.setText(r.getString("AddNewProductGUI.btnClear.text"));
        btnSave.setText(r.getString("AddNewProductGUI.btnSave.text"));
        jLabel4.setText(r.getString("AddNewProductGUI.jLabel4.text"));
    }//GEN-LAST:event_btnFrenchActionPerformed

    private void btnGermanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGermanActionPerformed
        // TODO add your handling code here:
        Locale l = new Locale("de", "DE");
        ResourceBundle r = ResourceBundle.getBundle("Bundle", l);
        jLabel3.setText(r.getString("AddNewProductGUI.jLabel3.text"));
        jLabel2.setText(r.getString("AddNewProductGUI.jLabel2.text"));
        jLabel1.setText(r.getString("AddNewProductGUI.jLabel1.text"));
        btnClear.setText(r.getString("AddNewProductGUI.btnClear.text"));
        btnSave.setText(r.getString("AddNewProductGUI.btnSave.text"));
        jLabel4.setText(r.getString("AddNewProductGUI.jLabel4.text"));
    }//GEN-LAST:event_btnGermanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewProductGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEnglish;
    private javax.swing.JButton btnFrench;
    private javax.swing.JButton btnGerman;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> txtCategory;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
