/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject2;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Ravindu
 */
public class HomeGUI extends javax.swing.JFrame {

    public String email;

    /**
     * Creates new form HomeGUI
     */
    public HomeGUI() {
        initComponents();
    }

    public HomeGUI(String userEmail) {
        initComponents();
        email = userEmail;
        if (!email.equals("admin@gmail.com")) {
            btnCategory.setVisible(false);
            btnNewProduct.setVisible(false);
            btnViewEditDeleteProduct.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnNewProduct = new javax.swing.JButton();
        btnViewEditDeleteProduct = new javax.swing.JButton();
        btnEnglish = new javax.swing.JButton();
        btnFrench = new javax.swing.JButton();
        btnGerman = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\logout.png")); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        jButton1.setText(bundle.getString("HomeGUI.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\place order.png")); // NOI18N
        jButton2.setText(bundle.getString("HomeGUI.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 250, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\exit small.png")); // NOI18N
        jButton5.setText(bundle.getString("HomeGUI.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1239, 25, -1, -1));

        btnCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCategory.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\category.png")); // NOI18N
        btnCategory.setText(bundle.getString("HomeGUI.btnCategory.text")); // NOI18N
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, -1, -1));

        btnNewProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNewProduct.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\new product.png")); // NOI18N
        btnNewProduct.setText(bundle.getString("HomeGUI.btnNewProduct.text")); // NOI18N
        btnNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, -1, -1));

        btnViewEditDeleteProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewEditDeleteProduct.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\view edit delete product.png")); // NOI18N
        btnViewEditDeleteProduct.setText(bundle.getString("HomeGUI.btnViewEditDeleteProduct.text")); // NOI18N
        btnViewEditDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEditDeleteProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewEditDeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 640, -1, -1));

        btnEnglish.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnglish.setText(bundle.getString("HomeGUI.btnEnglish.text")); // NOI18N
        btnEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnglishActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 50, -1));

        btnFrench.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFrench.setText(bundle.getString("HomeGUI.btnFrench.text")); // NOI18N
        btnFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrenchActionPerformed(evt);
            }
        });
        getContentPane().add(btnFrench, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 730, 50, -1));

        btnGerman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGerman.setText(bundle.getString("HomeGUI.btnGerman.text")); // NOI18N
        btnGerman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGermanActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerman, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 730, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\Coffee_Grain_Wood_planks_564164_1366x768.jpg")); // NOI18N
        jLabel1.setText(bundle.getString("HomeGUI.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here login:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new LogInGUI().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here exit:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Close Application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        // TODO add your handling code here:
        new ManageCategoryGUI().setVisible(true);
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductActionPerformed
        // TODO add your handling code here:
        new AddNewProductGUI().setVisible(true);
    }//GEN-LAST:event_btnNewProductActionPerformed

    private void btnViewEditDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEditDeleteProductActionPerformed
        // TODO add your handling code here:
        new ViewEditDeleteProductGUI().setVisible(true);
    }//GEN-LAST:event_btnViewEditDeleteProductActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PlaceOrderGUI(email).setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnglishActionPerformed
        // TODO add your handling code here:
        Locale l = new Locale("en", "US");
        ResourceBundle r = ResourceBundle.getBundle("Bundle", l);
        jButton1.setText(r.getString("HomeGUI.jButton1.text"));
        jButton2.setText(r.getString("HomeGUI.jButton2.text"));
        jButton5.setText(r.getString("HomeGUI.jButton5.text"));
        btnNewProduct.setText(r.getString("HomeGUI.btnNewProduct.text"));
        btnCategory.setText(r.getString("HomeGUI.btnCategory.text"));
        btnViewEditDeleteProduct.setText(r.getString("HomeGUI.btnViewEditDeleteProduct.text"));
    }//GEN-LAST:event_btnEnglishActionPerformed

    private void btnFrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrenchActionPerformed
        // TODO add your handling code here:
        Locale l = new Locale("fr", "FR");
        ResourceBundle r = ResourceBundle.getBundle("Bundle", l);
        jButton1.setText(r.getString("HomeGUI.jButton1.text"));
        jButton2.setText(r.getString("HomeGUI.jButton2.text"));
        jButton5.setText(r.getString("HomeGUI.jButton5.text"));
        btnNewProduct.setText(r.getString("HomeGUI.btnNewProduct.text"));
        btnCategory.setText(r.getString("HomeGUI.btnCategory.text"));
        btnViewEditDeleteProduct.setText(r.getString("HomeGUI.btnViewEditDeleteProduct.text"));
    }//GEN-LAST:event_btnFrenchActionPerformed

    private void btnGermanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGermanActionPerformed
        // TODO add your handling code here:
        Locale l = new Locale("de", "DE");
        ResourceBundle r = ResourceBundle.getBundle("Bundle", l);
        jButton1.setText(r.getString("HomeGUI.jButton1.text"));
        jButton2.setText(r.getString("HomeGUI.jButton2.text"));
        jButton5.setText(r.getString("HomeGUI.jButton5.text"));
        btnNewProduct.setText(r.getString("HomeGUI.btnNewProduct.text"));
        btnCategory.setText(r.getString("HomeGUI.btnCategory.text"));
        btnViewEditDeleteProduct.setText(r.getString("HomeGUI.btnViewEditDeleteProduct.text"));
    }//GEN-LAST:event_btnGermanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnEnglish;
    private javax.swing.JButton btnFrench;
    private javax.swing.JButton btnGerman;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnViewEditDeleteProduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
