/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject2;

import Dao.UserDao;
import Model.User;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ravindu
 */
public class LogInGUI extends javax.swing.JFrame {

    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";

    /**
     * Creates new form LogInGUI
     */
    public LogInGUI() {
        initComponents();
        btnLogIn.setEnabled(false);
    }

    public void clear() {
        txtEmail.setText("");
        txtPassword.setText("");
        btnLogIn.setEnabled(false);
    }

    public void validateFields() {
        String email = txtEmail.getText();
        String password = txtPassword.getText();
        if (email.matches(emailPattern) && !password.equals("")) {
            btnLogIn.setEnabled(true);
        } else {
            btnLogIn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnEnglish = new javax.swing.JButton();
        btnFrench = new javax.swing.JButton();
        btnGerman = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("LogInGUI.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(bundle.getString("LogInGUI.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(bundle.getString("LogInGUI.jLabel3.text")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 413, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 413, -1));

        btnLogIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogIn.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\login.png")); // NOI18N
        btnLogIn.setText(bundle.getString("LogInGUI.btnLogIn.text")); // NOI18N
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\clear.png")); // NOI18N
        btnClear.setText(bundle.getString("LogInGUI.btnClear.text")); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, -1, -1));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\exit small.png")); // NOI18N
        btnExit.setText(bundle.getString("LogInGUI.btnExit.text")); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, -1, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\login.png")); // NOI18N
        jButton5.setText(bundle.getString("LogInGUI.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 180, -1));

        btnEnglish.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnglish.setText(bundle.getString("LogInGUI.btnEnglish.text")); // NOI18N
        btnEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnglishActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 50, -1));

        btnFrench.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFrench.setText(bundle.getString("LogInGUI.btnFrench.text")); // NOI18N
        btnFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrenchActionPerformed(evt);
            }
        });
        getContentPane().add(btnFrench, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 730, 50, -1));

        btnGerman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGerman.setText(bundle.getString("LogInGUI.btnGerman.text")); // NOI18N
        btnGerman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGermanActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerman, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 730, 50, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\JavaProject\\JFrame Cafe Image & Icon\\Cafe Image & Icon\\images\\peakpx.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        String email = txtEmail.getText();
        String password = txtPassword.getText();
        User user = null;
        user = UserDao.logIn(email, password);
        if (user == null)
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:red\">Incorrect Username or Password</b></html>", "Message", JOptionPane.ERROR_MESSAGE);
        else {
            if (user.getStatus().equals("false")) {
                ImageIcon icon = new ImageIcon("src/popupicon/wait.png");
                JOptionPane.showMessageDialog(null, "<html><b style=\"color:green\">Wait for Admin Approval</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE, icon);
                clear();
            }
            if (user.getStatus().equals("true")) {
                setVisible(false);
                new HomeGUI(email).setVisible(true);
            }
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Are you sure?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new SignUpGUI().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnglishActionPerformed
        // TODO add your handling code here:
        Locale l = new Locale("en", "US");
        ResourceBundle r = ResourceBundle.getBundle("Bundle", l);
        jButton5.setText(r.getString("LogInGUI.jButton5.text"));
        btnExit.setText(r.getString("LogInGUI.btnExit.text"));
        btnClear.setText(r.getString("LogInGUI.btnClear.text"));
        btnLogIn.setText(r.getString("LogInGUI.btnLogIn.text"));
        jLabel3.setText(r.getString("LogInGUI.jLabel3.text"));
        jLabel2.setText(r.getString("LogInGUI.jLabel2.text"));
        jLabel1.setText(r.getString("LogInGUI.jLabel1.text"));

    }//GEN-LAST:event_btnEnglishActionPerformed

    private void btnFrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrenchActionPerformed
        // TODO add your handling code here:
        Locale l = new Locale("fr", "FR");
        ResourceBundle r = ResourceBundle.getBundle("Bundle", l);
        jButton5.setText(r.getString("LogInGUI.jButton5.text"));
        btnExit.setText(r.getString("LogInGUI.btnExit.text"));
        btnClear.setText(r.getString("LogInGUI.btnClear.text"));
        btnLogIn.setText(r.getString("LogInGUI.btnLogIn.text"));
        jLabel3.setText(r.getString("LogInGUI.jLabel3.text"));
        jLabel2.setText(r.getString("LogInGUI.jLabel2.text"));
        jLabel1.setText(r.getString("LogInGUI.jLabel1.text"));
    }//GEN-LAST:event_btnFrenchActionPerformed

    private void btnGermanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGermanActionPerformed
        // TODO add your handling code here:
        Locale l = new Locale("de", "DE");
        ResourceBundle r = ResourceBundle.getBundle("Bundle", l);
        jButton5.setText(r.getString("LogInGUI.jButton5.text"));
        btnExit.setText(r.getString("LogInGUI.btnExit.text"));
        btnClear.setText(r.getString("LogInGUI.btnClear.text"));
        btnLogIn.setText(r.getString("LogInGUI.btnLogIn.text"));
        jLabel3.setText(r.getString("LogInGUI.jLabel3.text"));
        jLabel2.setText(r.getString("LogInGUI.jLabel2.text"));
        jLabel1.setText(r.getString("LogInGUI.jLabel1.text"));
    }//GEN-LAST:event_btnGermanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEnglish;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFrench;
    private javax.swing.JButton btnGerman;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
